apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::848587260896:role/eksctl-eksops-nodegroup-ng-dover-NodeInstanceRole-1RUM3O1HIUKRR
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: "- userarn: arn:aws:iam::848587260896:user/k8s-admin\n  username: k8s-admin\n
    \ groups:     \n  - system:masters\n- userarn: arn:aws:iam::848587260896:user/k8s-user-2\n
    \ username: k8s-user-2\n  groups:       \n  - system:masters\n- userarn: arn:aws:iam::848587260896:user/k8s-user-prodadmin\n
    \ username: k8s-user-prodadmin\n  groups:\n  - role-prodadmin\n- userarn: arn:aws:iam::848587260896:user/k8s-user-prodviewer\n
    \ username: k8s-user-prodviewer\n  groups:       \n  - role-prodviewer\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::848587260896:role/eksctl-eksops-nodegroup-ng-dover-NodeInstanceRole-1RUM3O1HIUKRR\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::848587260896:user/k8s-admin\n  username: k8s-admin\n  groups:     \n  - system:masters\n- userarn: arn:aws:iam::848587260896:user/k8s-user-2\n  username: k8s-user-2\n  groups:       \n  - system:masters\n- userarn: arn:aws:iam::848587260896:user/k8s-user-prodadmin\n  username: k8s-user-prodadmin\n  groups:\n  - role-prodadmin\n- userarn: arn:aws:iam::848587260896:user/k8s-user-prodviewer\n  username: k8s-user-prodviewer\n  groups:       \n  - role-prodviewer\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2022-08-28T02:02:13Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"17317","uid":"1ca270f0-3657-4bfa-bd38-e1cfa932211a"}}
  creationTimestamp: "2022-08-28T02:02:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "23831"
  uid: 1ca270f0-3657-4bfa-bd38-e1cfa932211a
