apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: development
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - persistentvolumeclaims
  verbs:
  - list
  - create
  - watch
  - get
  - delete