apiVersion: v1
kind: Namespace
metadata:
  name: serviceaccounts
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-default-sa 
  namespace: serviceaccounts
spec:
  containers:
  - image: mongo:4.0.6
    name: mongodb