sudo: required

services:
  - docker

before_install:
  - docker build -t react-app -f dockerfile.dev .

script:
  - docker run -e CI=true react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "react-app-1"
  env: "react-app-1-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-848587260896"
  bucket_path: "react-app-1"
  on: 
    branch: master
  # edge: true 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY