
# This is the build-phase
FROM node:alpine as build-phase 
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# This is the run phase
FROM nginx
COPY --from=build-phase /app/build /usr/share/nginx/html
