apiVersion: eksctl.io/v1alpha5
# apiVersion: client.authentication.k8s.io/v1beta1
kind: ClusterConfig

metadata:
    version: "1.22"
    name: eksops
    region: ap-southeast-1 

nodeGroups:
    -   name: ng-dover
        instanceType: m5.large
        desiredCapacity: 3
        # minSize: 2  
        # maxSize: 5
        ssh: 
            publicKeyName: "k8s-kp"

# cloudWatch:
#     clusterLogging:
#         enableTypes:
#             - "api"
#             - "audit"
#             - "authenticator"        
