# Specify base image
FROM node:16

# Create app directory
WORKDIR /usr/app/nodejs

# Install some dependencies
COPY ./package.json ./
RUN npm install
COPY ./ ./

# Default command
CMD ["npm", "start"]