kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-new
  annotations:
    storageclass.kubernetes.io/is-default-class: "alse"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4  
reclaimPolicy: Retain
mountOptions:
  - debug