kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebind-prodadmin
  namespace: prod
# You can specify more than one "subject"
subjects:
- kind: User
  name: k8s-user-prodadmin # "name" is case sensitive
  apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: role-prodadmin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""
