apiVersion: eksctl.io/v1alpha5
# apiVersion: client.authentication.k8s.io/v1beta1
kind: ClusterConfig

metadata:
    version: "1.24"
    name: eksops-unmanaged
    region: ap-southeast-1 
nodeGroups:
    -   name: eksops-unmanaged
        instanceType: t3.micro
        minSize: 0
        maxSize: 5
        desiredCapacity: 3
        ssh: 
            publicKeyName: "k8s-kp"