apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-tcp
  labels:
    test: liveness
spec:
  replicas: 1
  selector:
    matchLabels:
      test: liveness  
  template:
    metadata:
      labels:
        test: liveness      
    spec:    
      containers:
      - name: liveness
        image: busybox:1.30.1
        ports:
        - containerPort: 8888
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 3
          periodSeconds: 5
        # Listen on port 8888 for 30 seconds, then sleep
        command: ["/bin/sh", "-c"]
        args: ["timeout 30 nc -p 8888 -lke echo hi && sleep 600"]