apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-http
  labels:
    test: readiness
spec:
  replicas: 1
  selector:
    matchLabels:
      test: readiness  
  template:
    metadata:
      labels:
        test: readiness      
    spec:    
      containers:
      - name: readiness
        image: httpd:2.4.38-alpine
        ports:
        - containerPort: 80
        # Sleep for 30 seconds before starting the server
        command: ["/bin/sh","-c"]
        args: ["sleep 30 && httpd-foreground"]
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3