apiVersion: eksctl.io/v1alpha5
# apiVersion: client.authentication.k8s.io/v1beta1
kind: ClusterConfig

metadata:
    version: "1.23"
    name: Cluster-1
    region: us-west-2
nodeGroups:
    -   name: Cluster-1
        instanceType: t3.large
        minSize: 0
        maxSize: 5
        desiredCapacity: 1
        ssh: 
            publicKeyName: "k8s-kp"